// this file was generated by the populateSurveyList.js script
module.exports = {
  surveys: [
    {
      end_time: "17:00",
      start_time: "09:00",
      name: "UCL Institute of Education Library",
      active: true,
      id: 46,
      maps: [
        {
          image_id: 79,
          name: "Level 3",
          id: 73,
        },
        {
          image_id: 80,
          name: "Level 4",
          id: 74,
        },
        {
          image_id: 81,
          name: "Level 5",
          id: 75,
        },
      ],
    },
    {
      end_time: "17:00",
      start_time: "09:00",
      name: "UCL Cruciform Hub",
      active: true,
      id: 45,
      maps: [
        {
          image_id: 78,
          name: "Open Area",
          id: 72,
        },
        {
          image_id: 76,
          name: "Cluster Areas",
          id: 70,
        },
        {
          image_id: 77,
          name: "Teaching Rooms",
          id: 71,
        },
      ],
    },
    {
      end_time: "17:00",
      start_time: "09:00",
      name: "The Joint Library of Ophthalmology",
      active: true,
      id: 40,
      maps: [
        {
          image_id: 65,
          name: "Ophthalmology Library",
          id: 61,
        },
      ],
    },
    {
      end_time: "17:00",
      start_time: "09:00",
      name: "UCL SSEES Library",
      active: true,
      id: 39,
      maps: [
        {
          image_id: 64,
          name: "SSEES Basement",
          id: 60,
        },
        {
          image_id: 84,
          name: "SSEES Ground Floor",
          id: 77,
        },
        {
          image_id: 63,
          name: "SSEES 1st Floor",
          id: 59,
        },
        {
          image_id: 85,
          name: "SSEES Second Floor",
          id: 78,
        },
      ],
    },
    {
      end_time: "17:00",
      start_time: "09:00",
      name: "UCL Main Library",
      active: true,
      id: 38,
      maps: [
        {
          image_id: 58,
          name: "1st East",
          id: 54,
        },
        {
          image_id: 59,
          name: "1st West",
          id: 55,
        },
        {
          image_id: 60,
          name: "Law Library",
          id: 56,
        },
        {
          image_id: 61,
          name: "2nd East",
          id: 57,
        },
        {
          image_id: 62,
          name: "2nd West",
          id: 58,
        },
      ],
    },
    {
      end_time: "17:00",
      start_time: "09:00",
      name: "UCL Senate House Hub",
      active: true,
      id: 35,
      maps: [
        {
          image_id: 52,
          name: "Senate House Hub",
          id: 51,
        },
      ],
    },
    {
      end_time: "17:00",
      start_time: "09:00",
      name: "UCL SENIT Suite",
      active: true,
      id: 33,
      maps: [
        {
          image_id: 53,
          name: "Senate Suit (Main)",
          id: 52,
        },
      ],
    },
    {
      end_time: "17:00",
      start_time: "09:00",
      name: "Royal Free Hospital Medical Library",
      active: true,
      id: 32,
      maps: [
        {
          image_id: 51,
          name: "Royal Free Hospital Library",
          id: 50,
        },
      ],
    },
    {
      end_time: "19:00",
      start_time: "09:00",
      name: "UCL Institute of Neurology, Queen Square Library",
      active: true,
      id: 28,
      maps: [
        {
          image_id: 35,
          name: "Neurology Library",
          id: 35,
        },
      ],
    },
    {
      end_time: "17:00",
      start_time: "09:00",
      name: "UCL School of Pharmacy Library",
      active: true,
      id: 27,
      maps: [
        {
          image_id: 37,
          name: "SoP First Floor",
          id: 37,
        },
      ],
    },
    {
      end_time: "17:00",
      start_time: "09:00",
      name: "UCL Wolfson Study",
      active: true,
      id: 22,
      maps: [
        {
          image_id: 3,
          name: "Wolfson Study",
          id: 3,
        },
      ],
    },
    {
      end_time: "17:00",
      start_time: "09:00",
      name: "UCL Science Library",
      active: true,
      id: 19,
      maps: [
        {
          image_id: 12,
          name: "Science Ground",
          id: 12,
        },
        {
          image_id: 13,
          name: "DMS Ground Mezzanine",
          id: 13,
        },
        {
          image_id: 14,
          name: "DMS First Floor",
          id: 14,
        },
        {
          image_id: 15,
          name: "DMS Second Floor",
          id: 15,
        },
        {
          image_id: 16,
          name: "DMS Third Floor",
          id: 16,
        },
        {
          image_id: 27,
          name: "DMS Fourth Floor",
          id: 25,
        },
      ],
    },
    {
      end_time: "19:00",
      start_time: "09:00",
      name: "UCL Ear Institute & Action on Hearing Loss Libraries",
      active: true,
      id: 16,
      maps: [
        {
          image_id: 48,
          name: "Hearing Library 1st",
          id: 47,
        },
        {
          image_id: 49,
          name: "Hearing Library Mez",
          id: 48,
        },
      ],
    },
    {
      end_time: "20:00",
      start_time: "09:00",
      name: "UCL Language & Speech Science Library",
      active: true,
      id: 14,
      maps: [
        {
          image_id: 83,
          name: "2nd Floor",
          id: 76,
        },
      ],
    },
    {
      end_time: "18:00",
      start_time: "09:00",
      name: "UCL Great Ormond Street Institute of Child Health Library",
      active: true,
      id: 12,
      maps: [
        {
          image_id: 7,
          name: "Child Health",
          id: 7,
        },
      ],
    },
    {
      end_time: "17:00",
      start_time: "09:00",
      name: "UCL Graduate Hub",
      active: true,
      id: 11,
      maps: [
        {
          image_id: 47,
          name: "Graduate Hub",
          id: 46,
        },
      ],
    },
    {
      end_time: "17:00",
      start_time: "09:00",
      name: "Foster Court B24 & B25",
      active: true,
      id: 10,
      maps: [
        {
          image_id: 4,
          name: "Foster Court",
          id: 4,
        },
      ],
    },
    {
      end_time: "17:00",
      start_time: "09:00",
      name: "UCL Eastman Dental Library",
      active: true,
      id: 9,
      maps: [
        {
          image_id: 44,
          name: "EDI Ground Floor",
          id: 43,
        },
      ],
    },
    {
      end_time: "20:00",
      start_time: "09:00",
      name: "UCL Bartlett Library",
      active: true,
      id: 8,
      maps: [
        {
          image_id: 6,
          name: "Bartlett Library",
          id: 6,
        },
      ],
    },
    {
      end_time: "21:00",
      start_time: "09:30",
      name: "UCL Institute of Archaeology Library",
      active: true,
      id: 7,
      maps: [
        {
          image_id: 2,
          name: "Archaeology",
          id: 2,
        },
      ],
    },
    {
      end_time: "17:00",
      start_time: "09:00",
      name: "UCL Anatomy Hub ",
      active: true,
      id: 6,
      maps: [
        {
          image_id: 5,
          name: "Anatomy Hub",
          id: 5,
        },
      ],
    },
  ],
  ok: true,
};
