export default {
  textColor: "#4D5061",
  lightTextColor: "#6E707F",
  pageBackground: "#fefefe",
  accentColor: "#1B998B",
  accentColorLight: "#73CCC2",
  textInputBackground: "#eaeaea",
  cardBackground: "#fff",
  buttonBackground: "#4BB3FD",
  disabledButtonBackground: "#9899a0",
  errorColor: "#D7263D",
  warningColor: "#AB7627",
  indicatorRed: "#FF0000",
  indicatorYellow: "#FFB800",
  indicatorGreen: "#6DD149",
};
