export const WORKSPACES_IS_FETCHING_SEATINFO =
  "WORKSPACES_IS_FETCHING_SEATINFO";
export const WORKSPACES_FETCH_SEATINFO_SUCCESS =
  "WORKSPACES_FETCH_SEATINFO_SUCCESS";
export const WORKSPACES_FETCH_SEATINFO_FAILURE =
  "WORKSPACES_FETCH_SEATINFO_FAILURE";
