export const TIMETABLE_IS_FETCHING = "TIMETABLE_IS_SIGNING_IN ";
export const TIMETABLE_FETCH_SUCCESS = "TIMETABLE_FETCH_SUCCESS";
export const TIMETABLE_FETCH_FAILURE = "TIMETABLE_FETCH_FAILURE";
export const CLEAR_TIMETABLE = "CLEAR_TIMETABLE";
export const TIMETABLE_CACHE_TIME_HOURS = 24;
