const { WORKSPACE_SURVEYS_URL } = require("../uclapi/constants");
const JSONRequest = require("../uclapi/JSONRequest");

if (!process.env.API_KEY) {
  console.error(
    "Error! You need to provide a UCL API key, using the API_KEY environment variable.",
  );
  process.exit(1);
}

const main = async () => {
  const res = await JSONRequest(
    `${WORKSPACE_SURVEYS_URL}?token=${process.env.API_KEY}`,
  );
  const str = JSON.stringify(res, "\n", 2);
  console.log("// this file was generated by the populateSurveyList.js script");
  console.log("module.exports = ");
  str.split("\n").forEach(line => console.log(line));
};

main();
